version: 1
handlers:
  console:
    class: logging.StreamHandler
    level: WARNING
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    filename: scip.log
loggers:
  matplotlib:
    level: ERROR
    handlers: [console]
  scip:
    level: DEBUG
    handlers: [file]
    propagate: 1
  
