name: Build
on: [push]
jobs:
  check_installation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install wheel flake8 pytest pytest-flake8
      - name: Install package
        run: |
          pip install .
      - name: Test with pytest (and lint with flake8)
        run: pytest --flake8